from flask import g, has_request_context


SUPPORTED_LANGUAGES = {"en", "fr", "ar"}


TRANSLATIONS = {
    "fr": {
        "Dashboard": "Accueil",
        "Transactions": "Transactions",
        "Budgets": "Budgets",
        "Savings": "Épargne",
        "Categories": "Catégories",
        "History": "Historique",
        "Settings": "Paramètres",
        "Profile & settings": "Profil et paramètres",
        "Menu": "Menu",
        "More": "Plus",
        "Close menu": "Fermer le menu",
        "Open menu": "Ouvrir le menu",
        "Primary navigation": "Navigation principale",
        "Log out": "Se déconnecter",
        "Light": "Clair",
        "Dark": "Sombre",
        "Use device setting": "Utiliser le réglage de l’appareil",
        "Appearance": "Apparence",
        "Language": "Langue",
        "English": "English",
        "French": "Français",
        "Arabic": "العربية",
        "Save preferences": "Enregistrer les préférences",
        "Appearance and language updated successfully.": "L’apparence et la langue ont été mises à jour.",
        "Email": "Adresse e-mail",
        "Password": "Mot de passe",
        "Confirm Password": "Confirmer le mot de passe",
        "Remember me": "Se souvenir de moi",
        "Log In": "Se connecter",
        "Create Account": "Créer un compte",
        "Welcome back": "Bon retour",
        "Log in to continue managing your money.": "Connectez-vous pour continuer à gérer votre argent.",
        "Don't have an account?": "Vous n’avez pas encore de compte ?",
        "Create one": "Créer un compte",
        "Create your account": "Créez votre compte",
        "Start with a clear view of your money.": "Commencez avec une vue claire de votre argent.",
        "Already have an account?": "Vous avez déjà un compte ?",
        "Log in": "Se connecter",
        "Create account": "Créer un compte",
        "Get started": "Commencer",
        "Start managing money": "Commencer à gérer mon argent",
        "See how it works": "Voir comment ça marche",
        "Money that makes sense, even when student life does not.": "Un budget clair, même quand la vie étudiante ne l’est pas.",
        "Track what comes in, plan what goes out, and know what is safe to spend without turning money into homework.": "Suivez ce qui entre, planifiez ce qui sort et sachez ce que vous pouvez dépenser sans transformer votre budget en devoir.",
        "Built for real student money": "Pensé pour le vrai budget étudiant",
        "Allowance, part-time work, irregular income, and everyday spending all belong in one calm place.": "Argent de poche, petit boulot, revenus irréguliers et dépenses quotidiennes restent réunis au même endroit.",
        "Start small": "Commencez simplement",
        "Add your balance and the categories that fit your life.": "Ajoutez votre solde et les catégories qui correspondent à votre quotidien.",
        "Stay aware": "Gardez le cap",
        "See your balance, budget, savings, and recent activity at a glance.": "Consultez votre solde, vos budgets, votre épargne et votre activité en un coup d’œil.",
        "Decide with confidence": "Décidez sereinement",
        "Safe-to-Spend keeps planned money visible before you use it.": "Le montant disponible protège l’argent déjà prévu avant de le dépenser.",
        "Your money, organized around student life.": "Votre argent, organisé autour de la vie étudiante.",
        "No bank connection. No complicated setup. Just the records and plans you choose to add.": "Aucune connexion bancaire ni configuration compliquée. Seulement les opérations et projets que vous choisissez d’ajouter.",
        "Ready when you are": "Prêt quand vous l’êtes",
        "Set up your account in a few short steps.": "Configurez votre compte en quelques étapes rapides.",
        "Made for students": "Pensé pour les étudiants",
        "Step {step} of 5": "Étape {step} sur 5",
        "Onboarding progress": "Progression de la configuration",
        "You can change this later.": "Vous pourrez modifier ce choix plus tard.",
        "Back": "Retour",
        "Continue": "Continuer",
        "Finish setup": "Terminer la configuration",
        "Your profile": "Votre profil",
        "Let's make this feel like yours": "Faisons de cet espace le vôtre",
        "Tell us what to call you and how you prefer to see your money.": "Indiquez votre nom et la devise dans laquelle afficher votre argent.",
        "Your first name or a nickname works perfectly.": "Un prénom ou un surnom suffit.",
        "We'll use this for balances, income, and spending.": "Cette devise sera utilisée pour les soldes, revenus et dépenses.",
        "Your goals": "Vos objectifs",
        "What would you like help with?": "Sur quoi voulez-vous progresser ?",
        "Choose as many as you like. We'll keep them as simple preferences.": "Choisissez autant d’objectifs que vous voulez. Ils resteront de simples préférences.",
        "Money coming in": "Argent reçu",
        "How do you receive money?": "Comment recevez-vous de l’argent ?",
        "Add regular income, one-off payments, or anything else you want to keep visible.": "Ajoutez les revenus réguliers, ponctuels ou tout autre montant que vous souhaitez garder en vue.",
        "Income source": "Source de revenu",
        "Source {number}": "Source {number}",
        "Remove": "Retirer",
        "Add another income source": "Ajouter une autre source",
        "Starting point": "Point de départ",
        "How much money do you have right now?": "Combien d’argent avez-vous maintenant ?",
        "Use the amount you currently consider available to spend or save.": "Utilisez le montant que vous considérez disponible pour dépenser ou épargner.",
        "A simple starting point": "Un point de départ simple",
        "You can update it later as your balance changes.": "Vous pourrez le modifier lorsque votre solde évoluera.",
        "Make your money feel organized": "Organisez votre argent à votre façon",
        "Keep the useful defaults, rename them, or add your own.": "Gardez les catégories utiles, renommez-les ou ajoutez les vôtres.",
        "Add category": "Ajouter une catégorie",
        "Your setup is almost ready.": "Votre configuration est presque terminée.",
        "Current balance": "Solde actuel",
        "Safe to spend": "Disponible à dépenser",
        "Available money": "Argent disponible",
        "Starting balance plus income, minus expenses.": "Solde initial plus revenus, moins dépenses.",
        "Transaction income": "Revenus enregistrés",
        "Transaction spending": "Dépenses enregistrées",
        "Planning estimate": "Estimation de planification",
        "Savings reserved": "Épargne réservée",
        "Budget reserved": "Budget réservé",
        "Budget & savings": "Budget et épargne",
        "Your plans": "Vos projets",
        "Based on your current records": "D’après vos données actuelles",
        "Manage budgets": "Gérer les budgets",
        "Manage savings": "Gérer l’épargne",
        "Quick actions": "Actions rapides",
        "Keep moving": "Continuer",
        "Add transaction": "Ajouter une transaction",
        "Record money in or out": "Enregistrer une entrée ou une sortie",
        "Add budget": "Ajouter un budget",
        "Plan an expense category": "Planifier une catégorie de dépense",
        "Add savings goal": "Ajouter un objectif d’épargne",
        "Start tracking a target": "Commencer à suivre un objectif",
        "Recent transactions": "Transactions récentes",
        "Activity": "Activité",
        "View transactions": "Voir les transactions",
        "View history": "Voir l’historique",
        "Next step": "Prochaine étape",
        "No transactions yet": "Aucune transaction pour le moment",
        "No budget set yet": "Aucun budget pour le moment",
        "No savings goals yet": "Aucun objectif d’épargne pour le moment",
        "Create a budget": "Créer un budget",
        "Create a savings goal": "Créer un objectif d’épargne",
        "All transactions": "Toutes les transactions",
        "Total transaction income": "Total des revenus enregistrés",
        "Total spending": "Dépenses totales",
        "Edit": "Modifier",
        "Delete": "Supprimer",
        "Cancel": "Annuler",
        "Save changes": "Enregistrer",
        "Expense": "Dépense",
        "Income": "Revenu",
        "Expenses": "Dépenses",
        "Choose a category": "Choisir une catégorie",
        "Choose an expense category": "Choisir une catégorie de dépense",
        "Transaction type": "Type de transaction",
        "Category": "Catégorie",
        "Amount": "Montant",
        "Description": "Description",
        "Transaction date": "Date de la transaction",
        "Today or an earlier date.": "Aujourd’hui ou une date antérieure.",
        "Enter a positive amount.": "Saisissez un montant positif.",
        "Optional, up to 255 characters.": "Facultatif, 255 caractères maximum.",
        "Category name": "Nom de la catégorie",
        "Category type": "Type de catégorie",
        "Type": "Type",
        "Icon": "Icône",
        "Color": "Couleur",
        "Choose an icon": "Choisir une icône",
        "Choose a color": "Choisir une couleur",
        "Custom color": "Couleur personnalisée",
        "Starter category": "Catégorie de départ",
        "Expense categories": "Catégories de dépense",
        "Income categories": "Catégories de revenu",
        "Budget period": "Période du budget",
        "Weekly": "Hebdomadaire",
        "Monthly": "Mensuel",
        "One time": "Une fois",
        "Irregular / manual": "Irrégulier / manuel",
        "Budget amount": "Montant du budget",
        "Budgeted": "Budgété",
        "Spent": "Dépensé",
        "Remaining": "Restant",
        "Over budget": "Budget dépassé",
        "Savings goals": "Objectifs d’épargne",
        "Saved": "Épargné",
        "Target": "Objectif",
        "Progress": "Progression",
        "Target date": "Date cible",
        "Completed": "Terminé",
        "Overdue": "En retard",
        "Add to savings": "Ajouter à l’épargne",
        "Withdraw from savings": "Retirer de l’épargne",
        "Filter transactions": "Filtrer les transactions",
        "Filters": "Filtres",
        "Clear filters": "Effacer les filtres",
        "Apply filters": "Appliquer",
        "From": "Du",
        "To": "Au",
        "Sort by": "Trier par",
        "Newest first": "Plus récentes d’abord",
        "Oldest first": "Plus anciennes d’abord",
        "Highest amount": "Montant le plus élevé",
        "Lowest amount": "Montant le plus faible",
        "Net": "Net",
        "Transaction history": "Historique des transactions",
        "Account": "Compte",
        "Money": "Argent",
        "Goals": "Objectifs",
        "Income sources": "Sources de revenu",
        "Display name": "Nom affiché",
        "Login email": "Adresse de connexion",
        "Currency": "Devise",
        "Starting balance": "Solde initial",
        "Save profile": "Enregistrer le profil",
        "Save money settings": "Enregistrer les réglages d’argent",
        "Save money goals": "Enregistrer les objectifs",
        "Add income source": "Ajouter une source de revenu",
        "Next payment date": "Prochaine date de paiement",
        "How often?": "À quelle fréquence ?",
        "Recurring": "Récurrent",
        "Non-recurring": "Non récurrent",
        "No payment date set": "Aucune date définie",
    },
    "ar": {
        "Dashboard": "الرئيسية",
        "Transactions": "المعاملات",
        "Budgets": "الميزانيات",
        "Savings": "الادخار",
        "Categories": "الفئات",
        "History": "السجل",
        "Settings": "الإعدادات",
        "Profile & settings": "الملف والإعدادات",
        "Menu": "القائمة",
        "More": "المزيد",
        "Close menu": "إغلاق القائمة",
        "Open menu": "فتح القائمة",
        "Primary navigation": "التنقل الرئيسي",
        "Log out": "تسجيل الخروج",
        "Light": "فاتح",
        "Dark": "داكن",
        "Use device setting": "استخدام إعداد الجهاز",
        "Appearance": "المظهر",
        "Language": "اللغة",
        "English": "English",
        "French": "Français",
        "Arabic": "العربية",
        "Save preferences": "حفظ التفضيلات",
        "Appearance and language updated successfully.": "تم تحديث المظهر واللغة.",
        "Email": "البريد الإلكتروني",
        "Password": "كلمة المرور",
        "Confirm Password": "تأكيد كلمة المرور",
        "Remember me": "تذكرني",
        "Log In": "تسجيل الدخول",
        "Create Account": "إنشاء حساب",
        "Welcome back": "مرحبًا بعودتك",
        "Log in to continue managing your money.": "سجل الدخول لمتابعة إدارة أموالك.",
        "Don't have an account?": "ليس لديك حساب؟",
        "Create one": "أنشئ حسابًا",
        "Create your account": "أنشئ حسابك",
        "Start with a clear view of your money.": "ابدأ برؤية واضحة لأموالك.",
        "Already have an account?": "لديك حساب بالفعل؟",
        "Log in": "تسجيل الدخول",
        "Create account": "إنشاء حساب",
        "Get started": "ابدأ الآن",
        "Start managing money": "ابدأ إدارة أموالك",
        "See how it works": "شاهد كيف يعمل",
        "Money that makes sense, even when student life does not.": "أموال مفهومة حتى عندما تكون حياة الطالب مزدحمة.",
        "Track what comes in, plan what goes out, and know what is safe to spend without turning money into homework.": "تابع ما يدخل، وخطط لما يخرج، واعرف ما يمكنك إنفاقه دون أن تصبح إدارة المال واجبًا إضافيًا.",
        "Built for real student money": "مصمم لواقع أموال الطلاب",
        "Allowance, part-time work, irregular income, and everyday spending all belong in one calm place.": "المصروف والعمل الجزئي والدخل غير المنتظم والنفقات اليومية كلها في مكان واحد هادئ.",
        "Start small": "ابدأ ببساطة",
        "Add your balance and the categories that fit your life.": "أضف رصيدك والفئات التي تناسب حياتك.",
        "Stay aware": "ابقَ على اطلاع",
        "See your balance, budget, savings, and recent activity at a glance.": "شاهد رصيدك وميزانيتك ومدخراتك ونشاطك الأخير بنظرة واحدة.",
        "Decide with confidence": "قرر بثقة",
        "Safe-to-Spend keeps planned money visible before you use it.": "المتاح للإنفاق يبقي الأموال المخطط لها واضحة قبل استخدامها.",
        "Your money, organized around student life.": "أموالك منظمة بما يناسب حياة الطالب.",
        "No bank connection. No complicated setup. Just the records and plans you choose to add.": "لا ربط بالبنك ولا إعداد معقد. فقط السجلات والخطط التي تختار إضافتها.",
        "Ready when you are": "ابدأ عندما تكون جاهزًا",
        "Set up your account in a few short steps.": "جهز حسابك في خطوات قصيرة.",
        "Made for students": "مصمم للطلاب",
        "Step {step} of 5": "الخطوة {step} من 5",
        "Onboarding progress": "تقدم الإعداد",
        "You can change this later.": "يمكنك تغيير هذا لاحقًا.",
        "Back": "رجوع",
        "Continue": "متابعة",
        "Finish setup": "إنهاء الإعداد",
        "Your profile": "ملفك",
        "Let's make this feel like yours": "لنجعل هذا المكان مناسبًا لك",
        "Tell us what to call you and how you prefer to see your money.": "أخبرنا بالاسم الذي تفضله والعملة التي تريد عرض أموالك بها.",
        "Your first name or a nickname works perfectly.": "يكفي اسمك الأول أو اسم مستعار.",
        "We'll use this for balances, income, and spending.": "سنستخدمها للأرصدة والدخل والإنفاق.",
        "Your goals": "أهدافك",
        "What would you like help with?": "بماذا تريد أن نساعدك؟",
        "Choose as many as you like. We'll keep them as simple preferences.": "اختر ما تشاء. سنحتفظ بها كتفضيلات بسيطة.",
        "Money coming in": "الأموال الواردة",
        "How do you receive money?": "كيف تستلم أموالك؟",
        "Add regular income, one-off payments, or anything else you want to keep visible.": "أضف الدخل المنتظم أو الدفعات لمرة واحدة أو أي مبلغ تريد إبقاءه واضحًا.",
        "Income source": "مصدر دخل",
        "Source {number}": "المصدر {number}",
        "Remove": "إزالة",
        "Add another income source": "إضافة مصدر دخل آخر",
        "Starting point": "نقطة البداية",
        "How much money do you have right now?": "كم تملك من المال الآن؟",
        "Use the amount you currently consider available to spend or save.": "استخدم المبلغ الذي تعتبره متاحًا للإنفاق أو الادخار الآن.",
        "A simple starting point": "نقطة بداية بسيطة",
        "You can update it later as your balance changes.": "يمكنك تحديثه لاحقًا عندما يتغير رصيدك.",
        "Make your money feel organized": "نظم أموالك بطريقتك",
        "Keep the useful defaults, rename them, or add your own.": "احتفظ بالفئات المفيدة أو أعد تسميتها أو أضف فئاتك.",
        "Add category": "إضافة فئة",
        "Your setup is almost ready.": "إعدادك أوشك على الاكتمال.",
        "Current balance": "الرصيد الحالي",
        "Safe to spend": "المتاح للإنفاق",
        "Available money": "المال المتاح",
        "Starting balance plus income, minus expenses.": "الرصيد الأولي زائد الدخل ناقص المصروفات.",
        "Transaction income": "الدخل المسجل",
        "Transaction spending": "الإنفاق المسجل",
        "Planning estimate": "تقدير للتخطيط",
        "Savings reserved": "الادخار المحجوز",
        "Budget reserved": "الميزانية المحجوزة",
        "Budget & savings": "الميزانية والادخار",
        "Your plans": "خططك",
        "Based on your current records": "بناءً على سجلاتك الحالية",
        "Manage budgets": "إدارة الميزانيات",
        "Manage savings": "إدارة الادخار",
        "Quick actions": "إجراءات سريعة",
        "Keep moving": "خطوتك التالية",
        "Add transaction": "إضافة معاملة",
        "Record money in or out": "سجل المال الداخل أو الخارج",
        "Add budget": "إضافة ميزانية",
        "Plan an expense category": "خطط لفئة مصروفات",
        "Add savings goal": "إضافة هدف ادخار",
        "Start tracking a target": "ابدأ متابعة هدف",
        "Recent transactions": "المعاملات الأخيرة",
        "Activity": "النشاط",
        "View transactions": "عرض المعاملات",
        "View history": "عرض السجل",
        "Next step": "الخطوة التالية",
        "No transactions yet": "لا توجد معاملات بعد",
        "No budget set yet": "لم تضف ميزانية بعد",
        "No savings goals yet": "لا توجد أهداف ادخار بعد",
        "Create a budget": "إنشاء ميزانية",
        "Create a savings goal": "إنشاء هدف ادخار",
        "All transactions": "كل المعاملات",
        "Total transaction income": "إجمالي الدخل المسجل",
        "Total spending": "إجمالي الإنفاق",
        "Edit": "تعديل",
        "Delete": "حذف",
        "Cancel": "إلغاء",
        "Save changes": "حفظ التغييرات",
        "Expense": "مصروف",
        "Income": "دخل",
        "Expenses": "المصروفات",
        "Choose a category": "اختر فئة",
        "Choose an expense category": "اختر فئة مصروفات",
        "Transaction type": "نوع المعاملة",
        "Category": "الفئة",
        "Amount": "المبلغ",
        "Description": "الوصف",
        "Transaction date": "تاريخ المعاملة",
        "Today or an earlier date.": "اليوم أو تاريخ سابق.",
        "Enter a positive amount.": "أدخل مبلغًا موجبًا.",
        "Optional, up to 255 characters.": "اختياري، بحد أقصى 255 حرفًا.",
        "Category name": "اسم الفئة",
        "Category type": "نوع الفئة",
        "Type": "النوع",
        "Icon": "الأيقونة",
        "Color": "اللون",
        "Choose an icon": "اختر أيقونة",
        "Choose a color": "اختر لونًا",
        "Custom color": "لون مخصص",
        "Starter category": "فئة أساسية",
        "Expense categories": "فئات المصروفات",
        "Income categories": "فئات الدخل",
        "Budget period": "فترة الميزانية",
        "Weekly": "أسبوعي",
        "Monthly": "شهري",
        "One time": "مرة واحدة",
        "Irregular / manual": "غير منتظم / يدوي",
        "Budget amount": "مبلغ الميزانية",
        "Budgeted": "المخصص",
        "Spent": "المنفق",
        "Remaining": "المتبقي",
        "Over budget": "تجاوز الميزانية",
        "Savings goals": "أهداف الادخار",
        "Saved": "المدخر",
        "Target": "الهدف",
        "Progress": "التقدم",
        "Target date": "تاريخ الهدف",
        "Completed": "مكتمل",
        "Overdue": "متأخر",
        "Add to savings": "إضافة للادخار",
        "Withdraw from savings": "سحب من الادخار",
        "Filter transactions": "تصفية المعاملات",
        "Filters": "عوامل التصفية",
        "Clear filters": "مسح التصفية",
        "Apply filters": "تطبيق",
        "From": "من",
        "To": "إلى",
        "Sort by": "الترتيب",
        "Newest first": "الأحدث أولًا",
        "Oldest first": "الأقدم أولًا",
        "Highest amount": "الأعلى مبلغًا",
        "Lowest amount": "الأقل مبلغًا",
        "Net": "الصافي",
        "Transaction history": "سجل المعاملات",
        "Account": "الحساب",
        "Money": "المال",
        "Goals": "الأهداف",
        "Income sources": "مصادر الدخل",
        "Display name": "اسم العرض",
        "Login email": "بريد تسجيل الدخول",
        "Currency": "العملة",
        "Starting balance": "الرصيد الأولي",
        "Save profile": "حفظ الملف",
        "Save money settings": "حفظ إعدادات المال",
        "Save money goals": "حفظ الأهداف",
        "Add income source": "إضافة مصدر دخل",
        "Next payment date": "تاريخ الدفعة التالية",
        "How often?": "كم مرة؟",
        "Recurring": "متكرر",
        "Non-recurring": "غير متكرر",
        "No payment date set": "لا يوجد تاريخ محدد",
    },
}


TRANSLATIONS["fr"].update({
    "Email must be 255 characters or fewer.": "L’adresse e-mail ne doit pas dépasser 255 caractères.",
    "Budget progress": "Progression du budget",
    "Savings progress": "Progression de l’épargne",
    "Page not found": "Page introuvable",
    "The page you requested could not be found.": "La page demandée est introuvable.",
    "Method not allowed": "Méthode non autorisée",
    "That action is not available for this request.": "Cette action n’est pas disponible pour cette requête.",
    "Something went wrong": "Un problème est survenu",
    "Please try again in a moment.": "Veuillez réessayer dans un instant.",
    "Return home": "Retour à l’accueil",
    "A calmer way to keep up with your money.": "Une façon plus sereine de suivre votre argent.",
    "A record you can understand in seconds.": "Un suivi compréhensible en quelques secondes.",
    "Add": "Ajouter",
    "Add / withdraw": "Ajouter / retirer",
    "Add a source to keep expected money visible.": "Ajoutez une source pour garder les revenus attendus en vue.",
    "Add your first transaction": "Ajouter votre première transaction",
    "Add your first transaction to begin building your history.": "Ajoutez votre première transaction pour commencer votre historique.",
    "Appearance and language": "Apparence et langue",
    "At least 8 characters": "Au moins 8 caractères",
    "budget": "budget",
    "budgets": "budgets",
    "Category limits": "Limites par catégorie",
    "Change color theme": "Changer le thème de couleur",
    "Changing the starting balance changes the calculated balance without creating a transaction.": "Modifier le solde initial change le solde calculé sans créer de transaction.",
    "Choose a name, type, icon, and small color cue.": "Choisissez un nom, un type, une icône et un repère de couleur discret.",
    "Choose a suggested color or open your device color picker.": "Choisissez une couleur proposée ou ouvrez le sélecteur de votre appareil.",
    "Clear the filters to return to your full history.": "Effacez les filtres pour retrouver tout votre historique.",
    "Current period": "Période actuelle",
    "Display unit only. Amounts are not converted.": "Unité d’affichage uniquement. Les montants ne sont pas convertis.",
    "e.g. Maya": "p. ex. Maya",
    "Edit budget": "Modifier le budget",
    "Edit category": "Modifier la catégorie",
    "Edit savings goal": "Modifier l’objectif d’épargne",
    "Edit transaction": "Modifier la transaction",
    "Explore activity": "Explorer l’activité",
    "Filtered": "Filtré",
    "Filtered history summary": "Résumé de l’historique filtré",
    "Find past activity without losing the full picture.": "Retrouvez une ancienne opération tout en gardant une vue d’ensemble.",
    "Food": "Alimentation",
    "Food budget": "Budget alimentation",
    "Here's your money overview.": "Voici l’essentiel de votre argent.",
    "How ILI pika addresses you": "Le nom utilisé par ILI pika",
    "Illustrative example": "Exemple illustratif",
    "Illustrative ILI pika money overview": "Exemple illustratif de l’aperçu ILI pika",
    "Income and expenses stay distinct through signs, labels, and layout, not color alone.": "Les revenus et dépenses se distinguent par les signes, libellés et la mise en page, pas seulement par la couleur.",
    "Income minus expenses": "Revenus moins dépenses",
    "Keep a clear record of money that entered or left your balance.": "Gardez une trace claire de l’argent entré ou sorti de votre solde.",
    "Keep your account, appearance, language, and money setup in one place.": "Gérez votre compte, l’apparence, la langue et vos réglages d’argent au même endroit.",
    "Laptop fund": "Projet ordinateur",
    "Ledger results": "Résultats du registre",
    "Money available before your tracked transactions.": "Argent disponible avant les transactions enregistrées.",
    "Money going out": "Argent dépensé",
    "Money you expect to receive": "Argent que vous prévoyez de recevoir",
    "No bank connection. No complicated setup.": "Aucune connexion bancaire ni configuration compliquée.",
    "No description": "Sans description",
    "No expense categories": "Aucune catégorie de dépense",
    "No income categories": "Aucune catégorie de revenu",
    "No income sources yet": "Aucune source de revenu pour le moment",
    "No transaction history yet": "Aucun historique pour le moment",
    "No transactions match these filters": "Aucune transaction ne correspond à ces filtres",
    "Optional. Leave blank to use your email.": "Facultatif. Laissez vide pour utiliser votre adresse e-mail.",
    "Organize the income and expenses you record.": "Organisez les revenus et dépenses que vous enregistrez.",
    "Plan spending limits using real expense transactions.": "Planifiez des limites à partir de vos dépenses réelles.",
    "Planning information only. It does not change your balance automatically.": "Information de planification uniquement. Votre solde ne change pas automatiquement.",
    "Record money that actually entered or left your available balance.": "Enregistrez l’argent réellement entré ou sorti de votre solde disponible.",
    "Remove category": "Retirer la catégorie",
    "Remove income source": "Retirer la source de revenu",
    "Repeat your password": "Répétez votre mot de passe",
    "Savings goal": "Objectif d’épargne",
    "savings goal": "objectif d’épargne",
    "Set a spending limit for one expense category.": "Fixez une limite pour une catégorie de dépense.",
    "Settings sections": "Sections des paramètres",
    "Shown": "Affichées",
    "shown": "affichées",
    "Skip to content": "Aller au contenu",
    "Source": "Source",
    "Student money, made clearer": "Le budget étudiant, plus clair",
    "Target reached": "Objectif atteint",
    "The saved theme and language follow your account on this device.": "Le thème et la langue enregistrés suivent votre compte sur cet appareil.",
    "These are preferences. Monetary targets stay on the Savings page.": "Ce sont des préférences. Les objectifs chiffrés restent dans Épargne.",
    "Track money set aside for personal targets without changing your transaction balance.": "Suivez l’argent réservé à vos projets sans modifier le solde des transactions.",
    "Track real transactions, protect your plans, and keep the next decision simple.": "Suivez vos vraies transactions, protégez vos projets et simplifiez la prochaine décision.",
    "transaction": "transaction",
    "Use icon": "Utiliser l’icône",
    "Use the amount available to you today.": "Utilisez le montant disponible aujourd’hui.",
    "Use your emoji keyboard or open the quick icon menu.": "Utilisez le clavier emoji ou ouvrez le menu d’icônes.",
    "What do you want to improve?": "Que voulez-vous améliorer ?",
    "You do not have a category for this transaction type yet.": "Vous n’avez pas encore de catégorie pour ce type de transaction.",
    "Your budgets": "Vos budgets",
    "Your financial starting point": "Votre point de départ financier",
    "Your interface": "Votre interface",
    "Your password": "Votre mot de passe",
    "Your targets": "Vos objectifs",
})

TRANSLATIONS["ar"].update({
    "Email must be 255 characters or fewer.": "يجب ألا يتجاوز البريد الإلكتروني 255 حرفًا.",
    "Budget progress": "تقدم الميزانية",
    "Savings progress": "تقدم الادخار",
    "Page not found": "الصفحة غير موجودة",
    "The page you requested could not be found.": "تعذر العثور على الصفحة المطلوبة.",
    "Method not allowed": "الطريقة غير مسموحة",
    "That action is not available for this request.": "هذا الإجراء غير متاح لهذا الطلب.",
    "Something went wrong": "حدث خطأ ما",
    "Please try again in a moment.": "يرجى المحاولة مرة أخرى بعد قليل.",
    "Return home": "العودة إلى الرئيسية",
    "A calmer way to keep up with your money.": "طريقة أهدأ لمتابعة أموالك.",
    "A record you can understand in seconds.": "سجل تفهمه خلال ثوانٍ.",
    "Add": "إضافة",
    "Add / withdraw": "إضافة / سحب",
    "Add a source to keep expected money visible.": "أضف مصدرًا لإبقاء الدخل المتوقع واضحًا.",
    "Add your first transaction": "أضف معاملتك الأولى",
    "Add your first transaction to begin building your history.": "أضف معاملتك الأولى لبدء إنشاء سجلك.",
    "Appearance and language": "المظهر واللغة",
    "At least 8 characters": "8 أحرف على الأقل",
    "budget": "ميزانية",
    "budgets": "ميزانيات",
    "Category limits": "حدود الفئات",
    "Change color theme": "تغيير نمط الألوان",
    "Changing the starting balance changes the calculated balance without creating a transaction.": "تغيير الرصيد الأولي يغير الرصيد المحسوب دون إنشاء معاملة.",
    "Choose a name, type, icon, and small color cue.": "اختر اسمًا ونوعًا وأيقونة وإشارة لونية بسيطة.",
    "Choose a suggested color or open your device color picker.": "اختر لونًا مقترحًا أو افتح منتقي الألوان في جهازك.",
    "Clear the filters to return to your full history.": "امسح عوامل التصفية للعودة إلى السجل الكامل.",
    "Current period": "الفترة الحالية",
    "Display unit only. Amounts are not converted.": "وحدة عرض فقط. لا يتم تحويل المبالغ.",
    "e.g. Maya": "مثال: مايا",
    "Edit budget": "تعديل الميزانية",
    "Edit category": "تعديل الفئة",
    "Edit savings goal": "تعديل هدف الادخار",
    "Edit transaction": "تعديل المعاملة",
    "Explore activity": "استكشف النشاط",
    "Filtered": "مصفّى",
    "Filtered history summary": "ملخص السجل المصفّى",
    "Find past activity without losing the full picture.": "اعثر على نشاط سابق مع الحفاظ على الصورة الكاملة.",
    "Food": "الطعام",
    "Food budget": "ميزانية الطعام",
    "Here's your money overview.": "هذه خلاصة أموالك.",
    "How ILI pika addresses you": "الاسم الذي يستخدمه ILI pika",
    "Illustrative example": "مثال توضيحي",
    "Illustrative ILI pika money overview": "مثال توضيحي لملخص أموال ILI pika",
    "Income and expenses stay distinct through signs, labels, and layout, not color alone.": "يظل الدخل والمصروف واضحين بالإشارات والتسميات والتخطيط، وليس باللون وحده.",
    "Income minus expenses": "الدخل ناقص المصروفات",
    "Keep a clear record of money that entered or left your balance.": "احتفظ بسجل واضح للمال الذي دخل رصيدك أو خرج منه.",
    "Keep your account, appearance, language, and money setup in one place.": "أدر حسابك ومظهرك ولغتك وإعدادات أموالك في مكان واحد.",
    "Laptop fund": "هدف الحاسوب",
    "Ledger results": "نتائج السجل",
    "Money available before your tracked transactions.": "المال المتاح قبل المعاملات المسجلة.",
    "Money going out": "الأموال الخارجة",
    "Money you expect to receive": "المال المتوقع استلامه",
    "No bank connection. No complicated setup.": "لا ربط بالبنك ولا إعداد معقد.",
    "No description": "دون وصف",
    "No expense categories": "لا توجد فئات مصروفات",
    "No income categories": "لا توجد فئات دخل",
    "No income sources yet": "لا توجد مصادر دخل بعد",
    "No transaction history yet": "لا يوجد سجل معاملات بعد",
    "No transactions match these filters": "لا توجد معاملات تطابق عوامل التصفية",
    "Optional. Leave blank to use your email.": "اختياري. اتركه فارغًا لاستخدام بريدك.",
    "Organize the income and expenses you record.": "نظم الدخل والمصروفات التي تسجلها.",
    "Plan spending limits using real expense transactions.": "خطط حدود الإنفاق باستخدام معاملات المصروفات الفعلية.",
    "Planning information only. It does not change your balance automatically.": "معلومات للتخطيط فقط. لا تغيّر رصيدك تلقائيًا.",
    "Record money that actually entered or left your available balance.": "سجل المال الذي دخل رصيدك المتاح أو خرج منه فعليًا.",
    "Remove category": "إزالة الفئة",
    "Remove income source": "إزالة مصدر الدخل",
    "Repeat your password": "أعد كتابة كلمة المرور",
    "Savings goal": "هدف ادخار",
    "savings goal": "هدف ادخار",
    "Set a spending limit for one expense category.": "حدد سقف إنفاق لفئة مصروفات واحدة.",
    "Settings sections": "أقسام الإعدادات",
    "Shown": "المعروض",
    "shown": "معروضة",
    "Skip to content": "انتقل إلى المحتوى",
    "Source": "المصدر",
    "Student money, made clearer": "أموال الطلاب بصورة أوضح",
    "Target reached": "تم بلوغ الهدف",
    "The saved theme and language follow your account on this device.": "يتبع المظهر واللغة المحفوظان حسابك على هذا الجهاز.",
    "These are preferences. Monetary targets stay on the Savings page.": "هذه تفضيلات. تبقى الأهداف المالية في صفحة الادخار.",
    "Track money set aside for personal targets without changing your transaction balance.": "تابع المال المخصص لأهدافك دون تغيير رصيد المعاملات.",
    "Track real transactions, protect your plans, and keep the next decision simple.": "تابع معاملاتك الحقيقية واحمِ خططك واجعل القرار التالي بسيطًا.",
    "transaction": "معاملة",
    "Use icon": "استخدام الأيقونة",
    "Use the amount available to you today.": "استخدم المبلغ المتاح لك اليوم.",
    "Use your emoji keyboard or open the quick icon menu.": "استخدم لوحة الرموز التعبيرية أو افتح قائمة الأيقونات السريعة.",
    "What do you want to improve?": "ما الذي تريد تحسينه؟",
    "You do not have a category for this transaction type yet.": "ليس لديك فئة لهذا النوع من المعاملات بعد.",
    "Your budgets": "ميزانياتك",
    "Your financial starting point": "نقطة بدايتك المالية",
    "Your interface": "واجهتك",
    "Your password": "كلمة مرورك",
    "Your targets": "أهدافك",
})

TRANSLATIONS["fr"].update({
    "Across budgeted expense categories": "Sur les catégories de dépense budgétées",
    "Add a spending limit for an expense category to begin tracking this period.": "Ajoutez une limite à une catégorie de dépense pour suivre cette période.",
    "Add money in or out to begin building your activity history.": "Ajoutez une entrée ou une sortie pour commencer votre historique.",
    "Add one before recording a new kind of expense.": "Ajoutez-en une avant d’enregistrer un nouveau type de dépense.",
    "Add one before recording a new source of income.": "Ajoutez-en une avant d’enregistrer une nouvelle source de revenu.",
    "Add your first transaction to begin building your recent activity.": "Ajoutez votre première transaction pour commencer votre activité récente.",
    "Available after protecting savings and remaining budget amounts.": "Disponible après avoir protégé l’épargne et les budgets restants.",
    "Create a budget to plan your current-period spending.": "Créez un budget pour planifier les dépenses de la période.",
    "Create a target for money set aside for something important to you.": "Créez un objectif pour l’argent réservé à un projet important.",
    "Currently saved": "Actuellement épargné",
    "Current-period spending in budgeted categories only.": "Dépenses de la période dans les catégories budgétées uniquement.",
    "Deleting a goal removes only its tracking record. It does not alter transactions, balances, categories, or budgets.": "Supprimer un objectif retire seulement son suivi. Les transactions, soldes, catégories et budgets ne changent pas.",
    "Edit income source": "Modifier la source de revenu",
    "Every expense category already has a budget, or no expense category exists.": "Chaque catégorie de dépense a déjà un budget, ou aucune catégorie n’existe.",
    "income source": "source de revenu",
    "Income sources are not included automatically": "Les sources de revenu ne sont pas ajoutées automatiquement",
    "Keep expected income visible without changing your transaction balance.": "Gardez les revenus attendus en vue sans modifier le solde des transactions.",
    "Only saved expense transactions": "Uniquement les dépenses enregistrées",
    "Only your expense categories can have budgets.": "Seules vos catégories de dépense peuvent avoir un budget.",
    "Optional. Past dates remain valid for missed targets.": "Facultatif. Une date passée reste valide pour un objectif manqué.",
    "Optional. Use today or a future date.": "Facultatif. Choisissez aujourd’hui ou une date future.",
    "Overfunded goals do not reduce other goals": "Un objectif dépassé ne réduit pas les autres",
    "Progress earmarked across all goals": "Somme réservée à tous les objectifs",
    "Saved amounts across your monetary targets.": "Montants épargnés sur vos objectifs chiffrés.",
    "Set a target for something you are working toward.": "Fixez un objectif pour un projet qui compte pour vous.",
    "Starting balance, plus income, minus expenses": "Solde initial, plus revenus, moins dépenses",
    "This source is scheduling information only. Saving it does not change your balance or create a transaction.": "Cette source sert uniquement à planifier. L’enregistrer ne modifie pas le solde et ne crée pas de transaction.",
    "This updates goal progress only. It does not create a transaction or change your available balance.": "Cela met à jour uniquement la progression. Aucune transaction n’est créée et le solde disponible ne change pas.",
    "through today.": "jusqu’à aujourd’hui.",
    "Unbudgeted expenses are not included here": "Les dépenses sans budget ne sont pas incluses ici",
    "Update saved amount": "Modifier le montant épargné",
    "Update savings": "Modifier l’épargne",
    "Your reserved savings and remaining budgets exceed your available balance by": "Votre épargne réservée et vos budgets restants dépassent votre solde disponible de",
    "Lunch": "Déjeuner",
    "Part-time work": "Petit boulot",
})

TRANSLATIONS["ar"].update({
    "Across budgeted expense categories": "عبر فئات المصروفات ذات الميزانية",
    "Add a spending limit for an expense category to begin tracking this period.": "أضف سقف إنفاق لفئة مصروفات لبدء متابعة هذه الفترة.",
    "Add money in or out to begin building your activity history.": "أضف مالًا داخلًا أو خارجًا لبدء سجل نشاطك.",
    "Add one before recording a new kind of expense.": "أضف فئة قبل تسجيل نوع جديد من المصروفات.",
    "Add one before recording a new source of income.": "أضف فئة قبل تسجيل مصدر دخل جديد.",
    "Add your first transaction to begin building your recent activity.": "أضف معاملتك الأولى لبدء نشاطك الأخير.",
    "Available after protecting savings and remaining budget amounts.": "المتاح بعد حماية الادخار ومبالغ الميزانية المتبقية.",
    "Create a budget to plan your current-period spending.": "أنشئ ميزانية لتخطيط إنفاق الفترة الحالية.",
    "Create a target for money set aside for something important to you.": "أنشئ هدفًا للمال المخصص لشيء مهم لك.",
    "Currently saved": "المدخر حاليًا",
    "Current-period spending in budgeted categories only.": "إنفاق الفترة الحالية في الفئات ذات الميزانية فقط.",
    "Deleting a goal removes only its tracking record. It does not alter transactions, balances, categories, or budgets.": "حذف الهدف يزيل سجل متابعته فقط ولا يغير المعاملات أو الأرصدة أو الفئات أو الميزانيات.",
    "Edit income source": "تعديل مصدر الدخل",
    "Every expense category already has a budget, or no expense category exists.": "كل فئات المصروفات لها ميزانية بالفعل، أو لا توجد فئة مصروفات.",
    "income source": "مصدر دخل",
    "Income sources are not included automatically": "لا تتم إضافة مصادر الدخل تلقائيًا",
    "Keep expected income visible without changing your transaction balance.": "أبقِ الدخل المتوقع واضحًا دون تغيير رصيد المعاملات.",
    "Only saved expense transactions": "معاملات المصروفات المحفوظة فقط",
    "Only your expense categories can have budgets.": "يمكن إضافة الميزانيات إلى فئات المصروفات فقط.",
    "Optional. Past dates remain valid for missed targets.": "اختياري. تظل التواريخ الماضية صالحة للأهداف الفائتة.",
    "Optional. Use today or a future date.": "اختياري. استخدم اليوم أو تاريخًا مستقبليًا.",
    "Overfunded goals do not reduce other goals": "زيادة تمويل هدف لا تقلل الأهداف الأخرى",
    "Progress earmarked across all goals": "المبلغ المخصص عبر كل الأهداف",
    "Saved amounts across your monetary targets.": "المبالغ المدخرة عبر أهدافك المالية.",
    "Set a target for something you are working toward.": "حدد هدفًا لشيء تعمل للوصول إليه.",
    "Starting balance, plus income, minus expenses": "الرصيد الأولي زائد الدخل ناقص المصروفات",
    "This source is scheduling information only. Saving it does not change your balance or create a transaction.": "هذا المصدر للمواعيد فقط. حفظه لا يغير رصيدك ولا ينشئ معاملة.",
    "This updates goal progress only. It does not create a transaction or change your available balance.": "يحدث هذا تقدم الهدف فقط ولا ينشئ معاملة أو يغير رصيدك المتاح.",
    "through today.": "حتى اليوم.",
    "Unbudgeted expenses are not included here": "المصروفات دون ميزانية غير مشمولة هنا",
    "Update saved amount": "تحديث المبلغ المدخر",
    "Update savings": "تحديث الادخار",
    "Your reserved savings and remaining budgets exceed your available balance by": "يتجاوز الادخار المحجوز والميزانيات المتبقية رصيدك المتاح بمقدار",
    "Lunch": "الغداء",
    "Part-time work": "عمل جزئي",
})

TRANSLATIONS["fr"].update({
    "Add your first transaction": "Ajouter votre première transaction",
    "Start tracking money that enters or leaves your balance.": "Commencez à suivre l’argent qui entre ou sort de votre solde.",
    "Review your reserved money": "Vérifier l’argent réservé",
    "Your planned savings and remaining budgets exceed your available balance.": "L’épargne prévue et les budgets restants dépassent votre solde disponible.",
    "Review budgets": "Vérifier les budgets",
    "Create a spending plan": "Créer un plan de dépenses",
    "Add a budget to plan your current-period spending.": "Ajoutez un budget pour planifier les dépenses de la période.",
    "Choose something to save toward": "Choisir un projet d’épargne",
    "Set a savings goal for something you are working toward.": "Fixez un objectif d’épargne pour un projet qui vous tient à cœur.",
    "Your overview is ready": "Votre aperçu est prêt",
    "Keep recording transactions so your money overview stays accurate.": "Continuez à enregistrer vos transactions pour garder un aperçu exact.",
})

TRANSLATIONS["ar"].update({
    "Add your first transaction": "أضف معاملتك الأولى",
    "Start tracking money that enters or leaves your balance.": "ابدأ متابعة المال الذي يدخل رصيدك أو يخرج منه.",
    "Review your reserved money": "راجع المال المحجوز",
    "Your planned savings and remaining budgets exceed your available balance.": "يتجاوز الادخار المخطط والميزانيات المتبقية رصيدك المتاح.",
    "Review budgets": "مراجعة الميزانيات",
    "Create a spending plan": "أنشئ خطة إنفاق",
    "Add a budget to plan your current-period spending.": "أضف ميزانية لتخطيط إنفاق الفترة الحالية.",
    "Choose something to save toward": "اختر هدفًا للادخار",
    "Set a savings goal for something you are working toward.": "حدد هدف ادخار لشيء تعمل للوصول إليه.",
    "Your overview is ready": "ملخصك جاهز",
    "Keep recording transactions so your money overview stays accurate.": "استمر في تسجيل المعاملات ليبقى ملخص أموالك دقيقًا.",
})

TRANSLATIONS["fr"].update({
    "Make steady progress toward a stronger cushion.": "Progressez régulièrement vers une réserve plus solide.",
    "Stay aware before small purchases add up.": "Restez attentif avant que les petits achats s’accumulent.",
    "See where your money is really going.": "Voyez clairement où va votre argent.",
    "Build routines that feel realistic and repeatable.": "Créez des habitudes réalistes et faciles à répéter.",
    "Keep a simple, reliable record of your money.": "Gardez un suivi simple et fiable de votre argent.",
    "Turn a specific plan into a reachable target.": "Transformez un projet précis en objectif atteignable.",
    "This field is required.": "Ce champ est obligatoire.",
    "Invalid email address.": "Adresse e-mail invalide.",
    "Field must be at least 8 characters long.": "Ce champ doit contenir au moins 8 caractères.",
    "Field must be equal to password.": "Les mots de passe doivent être identiques.",
    "Choose at least one goal.": "Choisissez au moins un objectif.",
    "Enter a valid amount.": "Saisissez un montant valide.",
    "Enter a category name.": "Saisissez un nom de catégorie.",
    "Choose an expense category.": "Choisissez une catégorie de dépense.",
    "Choose a category.": "Choisissez une catégorie.",
    "Enter a savings goal name.": "Saisissez un nom d’objectif d’épargne.",
    "Enter an income source name.": "Saisissez un nom de source de revenu.",
    "Enter an amount between 0.001 and 999,999,999.999.": "Saisissez un montant compris entre 0,001 et 999 999 999,999.",
    "Use a six-digit hex color such as #b6532e.": "Utilisez une couleur hexadécimale à six chiffres, comme #b6532e.",
    "Account created successfully!": "Compte créé.",
    "Invalid email or password.": "Adresse e-mail ou mot de passe incorrect.",
    "You have been logged out.": "Vous êtes déconnecté.",
    "That category already exists.": "Cette catégorie existe déjà.",
    "Category added successfully.": "Catégorie ajoutée.",
    "Category updated successfully.": "Catégorie mise à jour.",
    "Category deleted successfully.": "Catégorie supprimée.",
    "Please choose a valid category.": "Choisissez une catégorie valide.",
    "Transaction added successfully.": "Transaction ajoutée.",
    "Transaction updated successfully.": "Transaction mise à jour.",
    "Transaction deleted successfully.": "Transaction supprimée.",
    "Please choose a valid expense category.": "Choisissez une catégorie de dépense valide.",
    "That category already has a budget.": "Cette catégorie possède déjà un budget.",
    "Budget added successfully.": "Budget ajouté.",
    "Budget updated successfully.": "Budget mis à jour.",
    "Budget deleted successfully.": "Budget supprimé.",
    "Budget period updated successfully.": "Période du budget mise à jour.",
    "Profile updated successfully.": "Profil mis à jour.",
    "Money settings updated successfully.": "Réglages d’argent mis à jour.",
    "Money goals updated successfully.": "Objectifs mis à jour.",
    "Income source added successfully.": "Source de revenu ajoutée.",
    "Income source updated successfully.": "Source de revenu mise à jour.",
    "Income source deleted successfully.": "Source de revenu supprimée.",
    "Savings goal added successfully.": "Objectif d’épargne ajouté.",
    "Savings goal updated successfully.": "Objectif d’épargne mis à jour.",
    "Savings goal deleted successfully.": "Objectif d’épargne supprimé.",
    "Savings amount updated successfully.": "Montant épargné mis à jour.",
    "That withdrawal would make savings negative.": "Ce retrait rendrait l’épargne négative.",
    "That addition is larger than the supported limit.": "Cet ajout dépasse la limite acceptée.",
    "An account with that email already exists.": "Un compte utilise déjà cette adresse e-mail.",
    "A category with a budget must remain an expense category.": "Une catégorie avec un budget doit rester une catégorie de dépense.",
    "This category cannot be deleted because it is used by existing transactions.": "Cette catégorie ne peut pas être supprimée car des transactions l’utilisent.",
    "This category cannot be deleted because it has a budget.": "Cette catégorie ne peut pas être supprimée car elle possède un budget.",
    "This category cannot be deleted because it is used by existing transactions and a budget.": "Cette catégorie ne peut pas être supprimée car des transactions et un budget l’utilisent.",
})

TRANSLATIONS["ar"].update({
    "Make steady progress toward a stronger cushion.": "تقدم بثبات نحو احتياطي أقوى.",
    "Stay aware before small purchases add up.": "انتبه قبل أن تتراكم المشتريات الصغيرة.",
    "See where your money is really going.": "اعرف بوضوح أين تذهب أموالك.",
    "Build routines that feel realistic and repeatable.": "ابنِ عادات واقعية يسهل تكرارها.",
    "Keep a simple, reliable record of your money.": "احتفظ بسجل بسيط وموثوق لأموالك.",
    "Turn a specific plan into a reachable target.": "حوّل خطة محددة إلى هدف يمكن بلوغه.",
    "This field is required.": "هذا الحقل مطلوب.",
    "Invalid email address.": "عنوان البريد الإلكتروني غير صالح.",
    "Field must be at least 8 characters long.": "يجب ألا يقل هذا الحقل عن 8 أحرف.",
    "Field must be equal to password.": "يجب أن تتطابق كلمتا المرور.",
    "Choose at least one goal.": "اختر هدفًا واحدًا على الأقل.",
    "Enter a valid amount.": "أدخل مبلغًا صالحًا.",
    "Enter a category name.": "أدخل اسم الفئة.",
    "Choose an expense category.": "اختر فئة مصروفات.",
    "Choose a category.": "اختر فئة.",
    "Enter a savings goal name.": "أدخل اسم هدف الادخار.",
    "Enter an income source name.": "أدخل اسم مصدر الدخل.",
    "Enter an amount between 0.001 and 999,999,999.999.": "أدخل مبلغًا بين 0.001 و999,999,999.999.",
    "Use a six-digit hex color such as #b6532e.": "استخدم لونًا سداسيًا من ست خانات مثل #b6532e.",
    "Account created successfully!": "تم إنشاء الحساب.",
    "Invalid email or password.": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    "You have been logged out.": "تم تسجيل خروجك.",
    "That category already exists.": "هذه الفئة موجودة بالفعل.",
    "Category added successfully.": "تمت إضافة الفئة.",
    "Category updated successfully.": "تم تحديث الفئة.",
    "Category deleted successfully.": "تم حذف الفئة.",
    "Please choose a valid category.": "اختر فئة صالحة.",
    "Transaction added successfully.": "تمت إضافة المعاملة.",
    "Transaction updated successfully.": "تم تحديث المعاملة.",
    "Transaction deleted successfully.": "تم حذف المعاملة.",
    "Please choose a valid expense category.": "اختر فئة مصروفات صالحة.",
    "That category already has a budget.": "لهذه الفئة ميزانية بالفعل.",
    "Budget added successfully.": "تمت إضافة الميزانية.",
    "Budget updated successfully.": "تم تحديث الميزانية.",
    "Budget deleted successfully.": "تم حذف الميزانية.",
    "Budget period updated successfully.": "تم تحديث فترة الميزانية.",
    "Profile updated successfully.": "تم تحديث الملف.",
    "Money settings updated successfully.": "تم تحديث إعدادات المال.",
    "Money goals updated successfully.": "تم تحديث الأهداف المالية.",
    "Income source added successfully.": "تمت إضافة مصدر الدخل.",
    "Income source updated successfully.": "تم تحديث مصدر الدخل.",
    "Income source deleted successfully.": "تم حذف مصدر الدخل.",
    "Savings goal added successfully.": "تمت إضافة هدف الادخار.",
    "Savings goal updated successfully.": "تم تحديث هدف الادخار.",
    "Savings goal deleted successfully.": "تم حذف هدف الادخار.",
    "Savings amount updated successfully.": "تم تحديث مبلغ الادخار.",
    "That withdrawal would make savings negative.": "سيجعل هذا السحب مبلغ الادخار سالبًا.",
    "That addition is larger than the supported limit.": "تتجاوز هذه الإضافة الحد المدعوم.",
    "An account with that email already exists.": "يوجد حساب يستخدم هذا البريد الإلكتروني بالفعل.",
    "A category with a budget must remain an expense category.": "يجب أن تبقى الفئة المرتبطة بميزانية ضمن فئات المصروفات.",
    "This category cannot be deleted because it is used by existing transactions.": "لا يمكن حذف هذه الفئة لأن معاملات موجودة تستخدمها.",
    "This category cannot be deleted because it has a budget.": "لا يمكن حذف هذه الفئة لأنها مرتبطة بميزانية.",
    "This category cannot be deleted because it is used by existing transactions and a budget.": "لا يمكن حذف هذه الفئة لأن معاملات وميزانية تستخدمها.",
})

TRANSLATIONS["fr"].update({
    "What should we call you?": "Comment devons-nous vous appeler ?",
    "Your currency": "Votre devise",
    "Save category": "Enregistrer la catégorie",
    "Delete category": "Supprimer la catégorie",
    "Expense category": "Catégorie de dépense",
    "Save budget": "Enregistrer le budget",
    "Update period": "Modifier la période",
    "Delete budget": "Supprimer le budget",
    "Goal name": "Nom de l’objectif",
    "Target amount": "Montant cible",
    "Save goal": "Enregistrer l’objectif",
    "Action": "Action",
    "Update savings": "Modifier l’épargne",
    "Delete savings goal": "Supprimer l’objectif d’épargne",
    "Save transaction": "Enregistrer la transaction",
    "Delete transaction": "Supprimer la transaction",
    "Save income source": "Enregistrer la source de revenu",
    "Delete income source": "Supprimer la source de revenu",
    "Spending from": "Dépenses du",
    "Tunisian Dinar (TND)": "Dinar tunisien (TND)",
    "US Dollar (USD)": "Dollar américain (USD)",
    "Euro (EUR)": "Euro (EUR)",
    "Canadian Dollar (CAD)": "Dollar canadien (CAD)",
    "Delete this record? This cannot be undone.": "Supprimer cet élément ? Cette action est irréversible.",
})

TRANSLATIONS["ar"].update({
    "What should we call you?": "بماذا نناديك؟",
    "Your currency": "عملتك",
    "Save category": "حفظ الفئة",
    "Delete category": "حذف الفئة",
    "Expense category": "فئة المصروفات",
    "Save budget": "حفظ الميزانية",
    "Update period": "تحديث الفترة",
    "Delete budget": "حذف الميزانية",
    "Goal name": "اسم الهدف",
    "Target amount": "المبلغ المستهدف",
    "Save goal": "حفظ الهدف",
    "Action": "الإجراء",
    "Update savings": "تحديث الادخار",
    "Delete savings goal": "حذف هدف الادخار",
    "Save transaction": "حفظ المعاملة",
    "Delete transaction": "حذف المعاملة",
    "Save income source": "حفظ مصدر الدخل",
    "Delete income source": "حذف مصدر الدخل",
    "Spending from": "الإنفاق من",
    "Tunisian Dinar (TND)": "الدينار التونسي (TND)",
    "US Dollar (USD)": "الدولار الأمريكي (USD)",
    "Euro (EUR)": "اليورو (EUR)",
    "Canadian Dollar (CAD)": "الدولار الكندي (CAD)",
    "Delete this record? This cannot be undone.": "هل تريد حذف هذا السجل؟ لا يمكن التراجع عن هذا الإجراء.",
})

TRANSLATIONS["fr"].update({
    "Save more": "Épargner davantage",
    "Stop overspending": "Éviter les dépenses excessives",
    "Understand where my money goes": "Comprendre où va mon argent",
    "Build better money habits": "Prendre de meilleures habitudes",
    "Just track my money": "Simplement suivre mon argent",
    "Save for something specific": "Épargner pour un projet précis",
    "Transport": "Transport",
    "School": "Études",
    "Entertainment": "Loisirs",
    "Shopping": "Achats",
    "Other": "Autre",
    "Allowance": "Argent de poche",
    "Work": "Travail",
})

TRANSLATIONS["ar"].update({
    "Save more": "ادخار المزيد",
    "Stop overspending": "الحد من الإنفاق الزائد",
    "Understand where my money goes": "فهم أين تذهب أموالي",
    "Build better money habits": "بناء عادات مالية أفضل",
    "Just track my money": "متابعة أموالي فقط",
    "Save for something specific": "الادخار لهدف محدد",
    "Food": "الطعام",
    "Transport": "النقل",
    "School": "الدراسة",
    "Entertainment": "الترفيه",
    "Shopping": "التسوق",
    "Other": "أخرى",
    "Allowance": "المصروف",
    "Work": "العمل",
})

TRANSLATIONS["fr"].update({
    "Transaction totals": "Totaux des transactions",
    "Transaction summary": "Résumé des transactions",
    "Budget summary": "Résumé du budget",
    "Savings summary": "Résumé de l’épargne",
    "Dashboard quick actions": "Actions rapides du tableau de bord",
    "Transaction links": "Liens des transactions",
    "{percentage} percent used": "{percentage} % du budget utilisé",
    "{percentage} percent saved": "{percentage} % épargnés",
    "used": "utilisé",
    "saved": "épargnés",
    "saved overall": "épargnés au total",
    "over budget": "au-dessus du budget",
    "remaining": "restants",
    "beyond target": "au-delà de l’objectif",
    "{count} completed": "{count} terminés",
    "{count} active": "{count} actifs",
    "{count} still active": "{count} encore actifs",
    "{count} total": "{count} au total",
    "A positive amount in {currency}.": "Un montant positif en {currency}.",
    "A positive target amount in {currency}.": "Un montant cible positif en {currency}.",
    "e.g. Monthly allowance": "p. ex. Argent de poche mensuel",
    "Laptop": "Ordinateur portable",
    "What was this transaction for?": "À quoi correspond cette transaction ?",
    "Define a monetary target without changing your transaction ledger.": "Définissez un objectif financier sans modifier votre registre de transactions.",
    "Add to or withdraw from the progress tracked for {goal_name}.": "Ajoutez ou retirez un montant de la progression suivie pour {goal_name}.",
    "Category color {color}": "Couleur de la catégorie {color}",
    "This category is used by existing transactions or a budget.": "Cette catégorie est utilisée par des transactions ou un budget existants.",
    "Delete this goal record without changing transactions or balances.": "Supprimer cet objectif sans modifier les transactions ni les soldes.",
    "Next payment date cannot be in the past.": "La prochaine date de paiement ne peut pas être dans le passé.",
    "Balance must be between 0 and 999,999,999.999.": "Le solde doit être compris entre 0 et 999 999 999,999.",
    "Enter a balance between 0 and 999,999,999.999.": "Saisissez un solde compris entre 0 et 999 999 999,999.",
    "Transaction date cannot be in the future.": "La date de la transaction ne peut pas être dans le futur.",
    "The start date must be on or before the end date.": "La date de début doit être antérieure ou égale à la date de fin.",
    "Choose one of your categories matching the transaction type.": "Choisissez l’une de vos catégories correspondant au type de transaction.",
    "Choose one of your expense categories.": "Choisissez l’une de vos catégories de dépense.",
    "This category already has a budget.": "Cette catégorie possède déjà un budget.",
    "You cannot withdraw more than the amount currently saved.": "Vous ne pouvez pas retirer plus que le montant actuellement épargné.",
    "The resulting saved amount cannot exceed 999,999,999.999.": "Le montant épargné obtenu ne peut pas dépasser 999 999 999,999.",
    "Choose only the available money goals.": "Choisissez uniquement les objectifs financiers proposés.",
    "You already have a category with this name and type.": "Vous avez déjà une catégorie portant ce nom et ce type.",
    "Remove this category's budget before changing it to income.": "Supprimez le budget de cette catégorie avant de la convertir en catégorie de revenu.",
    "Not a valid choice.": "Ce choix n’est pas valide.",
})

TRANSLATIONS["ar"].update({
    "Transaction totals": "إجماليات المعاملات",
    "Transaction summary": "ملخص المعاملات",
    "Budget summary": "ملخص الميزانية",
    "Savings summary": "ملخص الادخار",
    "Dashboard quick actions": "الإجراءات السريعة في لوحة المعلومات",
    "Transaction links": "روابط المعاملات",
    "{percentage} percent used": "تم استخدام {percentage}% من الميزانية",
    "{percentage} percent saved": "تم ادخار {percentage}%",
    "used": "مستخدم",
    "saved": "مدخر",
    "saved overall": "مدخر إجمالًا",
    "over budget": "فوق الميزانية",
    "remaining": "متبقٍ",
    "beyond target": "فوق الهدف",
    "{count} completed": "{count} مكتملة",
    "{count} active": "{count} نشطة",
    "{count} still active": "{count} ما زالت نشطة",
    "{count} total": "الإجمالي: {count}",
    "A positive amount in {currency}.": "مبلغ موجب بعملة {currency}.",
    "A positive target amount in {currency}.": "مبلغ مستهدف موجب بعملة {currency}.",
    "e.g. Monthly allowance": "مثال: مصروف شهري",
    "Laptop": "حاسوب محمول",
    "What was this transaction for?": "ما الغرض من هذه المعاملة؟",
    "Define a monetary target without changing your transaction ledger.": "حدد هدفًا ماليًا دون تغيير سجل معاملاتك.",
    "Add to or withdraw from the progress tracked for {goal_name}.": "أضف إلى التقدم المسجل لهدف {goal_name} أو اسحب منه.",
    "Category color {color}": "لون الفئة {color}",
    "This category is used by existing transactions or a budget.": "تُستخدم هذه الفئة في معاملات أو ميزانية موجودة.",
    "Delete this goal record without changing transactions or balances.": "احذف سجل هذا الهدف دون تغيير المعاملات أو الأرصدة.",
    "Next payment date cannot be in the past.": "لا يمكن أن يكون تاريخ الدفعة التالية في الماضي.",
    "Balance must be between 0 and 999,999,999.999.": "يجب أن يكون الرصيد بين 0 و999,999,999.999.",
    "Enter a balance between 0 and 999,999,999.999.": "أدخل رصيدًا بين 0 و999,999,999.999.",
    "Transaction date cannot be in the future.": "لا يمكن أن يكون تاريخ المعاملة في المستقبل.",
    "The start date must be on or before the end date.": "يجب أن يكون تاريخ البداية قبل تاريخ النهاية أو مساويًا له.",
    "Choose one of your categories matching the transaction type.": "اختر فئة من فئاتك تطابق نوع المعاملة.",
    "Choose one of your expense categories.": "اختر فئة من فئات مصروفاتك.",
    "This category already has a budget.": "لهذه الفئة ميزانية بالفعل.",
    "You cannot withdraw more than the amount currently saved.": "لا يمكنك سحب مبلغ أكبر من المبلغ المدخر حاليًا.",
    "The resulting saved amount cannot exceed 999,999,999.999.": "لا يمكن أن يتجاوز المبلغ المدخر الناتج 999,999,999.999.",
    "Choose only the available money goals.": "اختر أهداف المال المتاحة فقط.",
    "You already have a category with this name and type.": "لديك بالفعل فئة بهذا الاسم والنوع.",
    "Remove this category's budget before changing it to income.": "احذف ميزانية هذه الفئة قبل تحويلها إلى فئة دخل.",
    "Not a valid choice.": "هذا الخيار غير صالح.",
})


TRANSLATABLE_CHOICE_VALUES = {
    "add",
    "all",
    "amount_high",
    "amount_low",
    "ar",
    "dark",
    "expense",
    "fr",
    "income",
    "light",
    "manual",
    "monthly",
    "newest",
    "oldest",
    "one_time",
    "system",
    "weekly",
    "withdraw",
    "TND",
    "USD",
    "EUR",
    "CAD",
    "save_more",
    "stop_overspending",
    "understand_spending",
    "better_habits",
    "track_money",
    "save_for_something",
}


def current_language():
    if has_request_context():
        language = getattr(g, "language", "en")
        if language in SUPPORTED_LANGUAGES:
            return language
    return "en"


def translate_text(text, **values):
    source = str(text)
    language = current_language()
    translated = TRANSLATIONS.get(language, {}).get(source, source)

    if values:
        try:
            return translated.format(**values)
        except (KeyError, ValueError):
            return translated

    return translated


def translate(text, **values):
    return translate_text(text, **values)


DEFAULT_CATEGORY_NAMES = {
    "Food",
    "Transport",
    "School",
    "Entertainment",
    "Shopping",
    "Other",
    "Allowance",
    "Work",
}


def category_name(category):
    if category.is_default and category.name in DEFAULT_CATEGORY_NAMES:
        return translate_text(category.name)
    return category.name


MONTH_NAMES = {
    "en": [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ],
    "fr": [
        "janvier", "février", "mars", "avril", "mai", "juin",
        "juillet", "août", "septembre", "octobre", "novembre", "décembre",
    ],
    "ar": [
        "يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو",
        "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر",
    ],
}


def format_date(value):
    if value is None:
        return ""

    language = current_language()
    month = MONTH_NAMES[language][value.month - 1]
    if language == "en":
        return f"{month} {value.day}, {value.year}"
    return f"{value.day} {month} {value.year}"


def localize_form(form):
    for field in form:
        field.label.text = translate_text(field.label.text)

        if getattr(field, "choices", None):
            field.choices = [
                (
                    value,
                    translate_text(label)
                    if str(value) in TRANSLATABLE_CHOICE_VALUES or value == 0
                    else label,
                )
                for value, label in field.choices
            ]

        for entry in getattr(field, "entries", []):
            nested_form = getattr(entry, "form", None)
            if nested_form is not None:
                localize_form(nested_form)
