"""Add user settings and onboarding status

Revision ID: aa301d50045d
Revises: 60318e859372
Create Date: 2026-08-08 14:34:57.715611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa301d50045d'
down_revision = '60318e859372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='TND', nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=12, scale=3), server_default='0.000', nullable=False),
    sa.Column('budget_period', sa.String(length=20), server_default='monthly', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    op.drop_table('user_settings')
    # ### end Alembic commands ###
